In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/Telco-Customer-Churn.csv")
print(df.shape)
df.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df["Churn"].value_counts(normalize=True).round(3)

Churn
No     0.735
Yes    0.265
Name: proportion, dtype: float64

In [6]:
print(df["TotalCharges"].dtype)
print((df["TotalCharges"].str.strip() == "").sum())

str
11

In [8]:
df[df["TotalCharges"].str.strip() == ""][["tenure", "MonthlyCharges"]]

      tenure  MonthlyCharges
488        0           52.55
753        0           20.25
936        0           80.85
1082       0           25.75
1340       0           56.05
3331       0           19.85
3826       0           25.35
4380       0           20.00
5218       0           19.70
6670       0           73.35
6754       0           61.90

In [10]:
(df.groupby("Contract")["Churn"]
.value_counts(normalize=True)
.unstack()
.round(3))

Churn              No    Yes
Contract
Month-to-month  0.573  0.427
One year        0.887  0.113
Two year        0.972  0.028

In [11]:
print(df["customerID"].nunique(), "unique IDs in", len(df), "rows")

7043 unique IDs in 7043 rows